# Generated by Django 4.0.4 on 2022-05-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredientes', '0003_remove_ingrediente_porcao_ingrediente_quantidade'),
        ('etapas', '0002_etapa_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descriacao', models.TextField(verbose_name='Descrição')),
                ('etapas', models.ManyToManyField(blank=True, null=True, related_name='receita_etapas', to='etapas.etapa', verbose_name='Etapas')),
                ('ingredientes', models.ManyToManyField(blank=True, null=True, related_name='receita_ingredientes', to='ingredientes.ingrediente', verbose_name='Ingredientes')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
    ]
