# Generated by Django 4.0.4 on 2022-05-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0002_etapa_ordem'),
        ('ingredientes', '0003_remove_ingrediente_porcao_ingrediente_quantidade'),
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='etapas',
            field=models.ManyToManyField(related_name='receita_etapas', to='etapas.etapa', verbose_name='Etapas'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.ManyToManyField(related_name='receita_ingredientes', to='ingredientes.ingrediente', verbose_name='Ingredientes'),
        ),
    ]
