# Generated by Django 4.0.4 on 2022-05-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='ordem',
            field=models.IntegerField(default=1, verbose_name='Ordem'),
            preserve_default=False,
        ),
    ]
