# Generated by Django 4.0.4 on 2022-05-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='porcao',
            field=models.CharField(default=1, max_length=100, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
