# Generated by Django 4.0.4 on 2022-05-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_remove_ingrediente_quantidade_ingrediente_porcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='porcao',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='quantidade',
            field=models.CharField(default=1, max_length=255, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
